### ISSUE TITLE
First time scrolling image does not fit correctly

### ISSUE THREAD

**Issue by andreyluiz** [daimajia/AndroidImageSlider#208]
I have a SliderLayout set with a 4 DefaultSliderViews. The images are set with BaseSliderView.ScaleType.CenterCrop scale type setting. 

The first time an image loads, it does not seems to be like my scale type setting sets. 

This is the image in the fresh new activity loaded (first time):

![First time](https://i.imgsafe.org/dc908da.png)

Notice the white space in the left and right borders.

When the slider runs and the same image appears again, it becomes different, as follows:

![Second time](https://i.imgsafe.org/d2cb9c8.png)

As far as I know, the right image must be the one that comes in the second slider loop. With no borders.

Does anyone knows what is happening?

**Comment by anamariamiehs** [comment]
I had the exact same scaleType problem when resuming my fragment from another fragment. 
I know it's a particular solution, however maybe it will help someone, since appending my new fragment was disrupting the slider creation in onCreateView: 

if (something)
 // append Fragment or whatever you wish to do
else {
// add slides to slider
}
